### ISSUE TITLE
Music Disks do not use the Jukebox/Note Blocks audio channel

### ISSUE THREAD

**Issue by StaticSapphic** [Shoxie12/MCDJ#10]
Music disks made through this mod play incredibly loud, and adjusting the jukebox volume settings does not affect this, only the master volume.

Additionally, music does not get quieter the further away from the jukebox you are, unlike vanilla music disks

I am not entirely sure if this is a bug or not but would you be able to add these features? Thanks

**Comment by Shoxie12** [comment]
Unfortunatelly, these issues can't be fixed because it's all about jukebox.
Jukebox plays all music discs loudly. Louder than playing with / playsound. Try to set the volume to 5 - 1%

Also Minecraft does not work well with music converted to stereo. You will hear music wherever you are.
But if you convert .ogg files in mono, this will solve the problem.

**Comment by StaticSapphic** [comment]
Converted songs to mono using Audacity, that fixed it thanks!
>Minecraft does not work well with music converted to stereo. You will hear music wherever you are.
But if you convert .ogg files in mono, this will solve the problem.

Could you add this to the wiki? I feel like this would be useful for new players

**Comment by Shoxie12** [comment]
Thanks for the suggestion, I added corrections to the wiki
